import type { CategorySlug } from "./categories"

export interface Program {
  readonly id: string
  readonly category: CategorySlug
  readonly name: string
  readonly icon: string
  readonly description: string
  readonly ageRange: string
  readonly duration: string
  readonly instructors: string
}

export const programs: readonly Program[] = [
  // === SPORT (8) ===
  {
    id: "zimni-sporty",
    category: "sport",
    name: "Zimní sporty",
    icon: "⛷️",
    description: "Lyžování, sáňkování, bruslení.",
    ageRange: "MŠ–ZŠ 2. st.",
    duration: "Celý den",
    instructors: "2–4",
  },
  {
    id: "basketbal",
    category: "sport",
    name: "Basketbal",
    icon: "🏀",
    description: "Hravý úvod, koordinace, týmová spolupráce.",
    ageRange: "1.–9. třída",
    duration: "90 min",
    instructors: "1–2",
  },
  {
    id: "atletika",
    category: "sport",
    name: "Atletika",
    icon: "🏃‍♂️",
    description: "Sprint, skok, hod. Celý trojboj.",
    ageRange: "1.–9. třída",
    duration: "2–4 hod",
    instructors: "2",
  },
  {
    id: "gymnastika",
    category: "sport",
    name: "Gymnastika",
    icon: "🤸‍♀️",
    description: "Obratnost, rovnováha, koordinace.",
    ageRange: "MŠ–5. třída",
    duration: "60–90 min",
    instructors: "2",
  },
  {
    id: "plavani",
    category: "sport",
    name: "Plavání",
    icon: "🏊‍♂️",
    description: "Základy plavání a vodní bezpečnosti.",
    ageRange: "MŠ–6. třída",
    duration: "60 min",
    instructors: "2–3",
  },
  {
    id: "inline-brusleni",
    category: "sport",
    name: "Inline bruslení",
    icon: "🛼",
    description: "Od základů po jízdu v pohybu.",
    ageRange: "MŠ–6. třída",
    duration: "90–120 min",
    instructors: "2",
  },
  {
    id: "upolove-sporty",
    category: "sport",
    name: "Úpolové sporty",
    icon: "🥋",
    description: "Judo, sebeobrana. Fair play a respekt.",
    ageRange: "3.–9. třída",
    duration: "90 min",
    instructors: "1–2",
  },
  {
    id: "hazena",
    category: "sport",
    name: "Házená",
    icon: "🤾‍♂️",
    description: "Základy a taktika. Týmová hra.",
    ageRange: "3.–9. třída",
    duration: "90 min",
    instructors: "1–2",
  },

  // === VZDĚLÁVÁNÍ (7) ===
  {
    id: "prvni-pomoc",
    category: "vzdelavani",
    name: "První pomoc",
    icon: "🩺",
    description: "Nácvik resuscitace a ošetření ran.",
    ageRange: "3.–9. třída",
    duration: "90–180 min",
    instructors: "1–2",
  },
  {
    id: "matematika-hrave",
    category: "vzdelavani",
    name: "Matematika hravě",
    icon: "🧮",
    description: "Hry, logické úlohy, zážitky.",
    ageRange: "MŠ–5. třída",
    duration: "60–90 min",
    instructors: "1",
  },
  {
    id: "cestina-hrave",
    category: "vzdelavani",
    name: "Čeština hravě",
    icon: "📖",
    description: "Hry, dramatizace, čtení.",
    ageRange: "MŠ–4. třída",
    duration: "60–90 min",
    instructors: "1",
  },
  {
    id: "emocni-inteligence",
    category: "vzdelavani",
    name: "Emoční inteligence",
    icon: "🫂",
    description: "Empatie, sebeuvědomění.",
    ageRange: "1.–9. třída",
    duration: "90–120 min",
    instructors: "1–2",
  },
  {
    id: "prevence-sikany",
    category: "vzdelavani",
    name: "Prevence šikany",
    icon: "🛡️",
    description: "Bezpečné vztahy, hranice, konflikty.",
    ageRange: "3.–9. třída",
    duration: "90–120 min",
    instructors: "2",
  },
  {
    id: "digitalni-gramotnost",
    category: "vzdelavani",
    name: "Digitální gramotnost",
    icon: "💻",
    description: "Bezpečný internet, mediální výchova.",
    ageRange: "4.–9. třída",
    duration: "90 min",
    instructors: "1",
  },
  {
    id: "zdravy-zivotni-styl",
    category: "vzdelavani",
    name: "Zdravý životní styl",
    icon: "🍎",
    description: "Výživa, pohyb, správné návyky.",
    ageRange: "MŠ–ZŠ",
    duration: "90 min",
    instructors: "1",
  },

  // === PROJEKTOVÉ DNY (5) ===
  {
    id: "sportovni-olympiada",
    category: "projektove-dny",
    name: "Sportovní olympiáda",
    icon: "🏅",
    description: "Celoškolní disciplíny pro každou třídu.",
    ageRange: "Celá škola",
    duration: "Celý den",
    instructors: "4–6",
  },
  {
    id: "den-pohybu",
    category: "projektove-dny",
    name: "Den pohybu",
    icon: "🎽",
    description: "Pohybové hry, překážkové dráhy.",
    ageRange: "MŠ–ZŠ",
    duration: "Celý den",
    instructors: "3–4",
  },
  {
    id: "den-zdravi",
    category: "projektove-dny",
    name: "Den zdraví",
    icon: "💪",
    description: "Strava, pohyb, spánek. Vzdělávací i pohybový.",
    ageRange: "MŠ–ZŠ",
    duration: "Celý den",
    instructors: "2–4",
  },
  {
    id: "tymovy-den",
    category: "projektove-dny",
    name: "Týmový den",
    icon: "🤝",
    description: "Teambuilding pro třídu. Spolupráce a komunikace.",
    ageRange: "3.–9. třída",
    duration: "Celý den",
    instructors: "2",
  },
  {
    id: "den-prirody",
    category: "projektove-dny",
    name: "Den přírody",
    icon: "🍃",
    description: "Orientace, příroda, udržitelnost. Venkovní.",
    ageRange: "MŠ–6. třída",
    duration: "Celý den",
    instructors: "3–4",
  },

  // === AKCE A POBYTY (6) ===
  {
    id: "lyzarsky-kurz",
    category: "akce",
    name: "Lyžařský kurz",
    icon: "🎿",
    description: "Kompletní organizace lyžáků.",
    ageRange: "ZŠ 4.–9. třída",
    duration: "5–7 dní",
    instructors: "4–8",
  },
  {
    id: "vodacky-kurz",
    category: "akce",
    name: "Vodácký kurz",
    icon: "🛶",
    description: "Kánoe, bezpečnost na vodě.",
    ageRange: "ZŠ 5.–9. třída",
    duration: "3–5 dní",
    instructors: "3–5",
  },
  {
    id: "skola-v-prirode",
    category: "akce",
    name: "Škola v přírodě",
    icon: "🌲",
    description: "Vzdělávací + sportovní program.",
    ageRange: "MŠ–ZŠ",
    duration: "3–5 dní",
    instructors: "2–4",
  },
  {
    id: "letni-tabor",
    category: "akce",
    name: "Letní tábor",
    icon: "⛺",
    description: "Bohatý program, výlety.",
    ageRange: "6–15 let",
    duration: "7–14 dní",
    instructors: "4–8",
  },
  {
    id: "sportovni-soustredeni",
    category: "akce",
    name: "Sportovní soustředění",
    icon: "🏋️‍♂️",
    description: "Intenzivní trénink.",
    ageRange: "ZŠ 4.–9. třída",
    duration: "3–5 dní",
    instructors: "2–4",
  },
  {
    id: "zajmove-krouzky",
    category: "akce",
    name: "Zájmové kroužky",
    icon: "🎯",
    description: "Celoroční, přímo ve škole.",
    ageRange: "MŠ–ZŠ",
    duration: "Celoroční",
    instructors: "1",
  },
] as const
